#!/usr/bin/env python3

import numpy as np
import serial
import time
import datetime
import sys
sys.stdout.flush()

def myprint(string):
    print(string, flush=True)

# Find total time
start_time = str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
if len(sys.argv) == 1:
    multiplier = 1.0
    myprint('STARTED AT: '+start_time)
    myprint('3 HOUR PROGRAM STARTING')
else:
    multiplier = float(sys.argv[1])
    myprint('STARTED AT: '+start_time)
    myprint(str(np.round(multiplier*3, 2))+' HOUR PROGRAM STARTING')

# Definitions
baud = 9600
#port = "/dev/tty.usbserial-ftDDL0UJ"
port = "/dev/ttyUSB0"

def write(serial, string):
    write_string = string+'\r\n'
    serial.write(write_string.encode('ascii'))

# Open serial port
try:
    s = serial.Serial(port, baud, timeout=1)
except:
    myprint('Serial port not found. Check port name.')
    exit()
if s.isOpen():
    write(s, 'SYSTEM:REMOTE')
    myprint(s.name + ' is open...')
else:
    myprint('Serial port error.')
    exit()

# Main script
myprint("PHASE 1: SIN 10 HZ 0.05 - 1.14 VPP RAMP 30 MIN")
write(s, 'FUNC:SHAP SIN')
write(s, 'FREQ 10')
for i in range(30):
    myprint('PHASE 1: ' + str(i) + '/30 MIN')
    voltage = np.round((i/(30-1))*(1.14 - 0.05) + 0.05, 2)
    write(s, 'VOLT '+str(voltage))
    time.sleep(60*multiplier)
    
myprint("PHASE 2: SIN 10 HZ 1.14 VPP 120 MIN")
write(s, 'FUNC:SHAP SIN')
write(s, 'FREQ 10')
for i in range(120):
    myprint('PHASE 2: ' + str(i) + '/120 MIN')
    write(s, 'VOLT 1.14')
    time.sleep(60*multiplier)
    
myprint("PHASE 3: SQU 4.5 HZ 2.12 VPP 30 MIN")
write(s, 'FUNC:SHAP SQU')
write(s, 'FREQ 4.5')
write(s, 'VOLT 2.12')
for i in range(30):
    myprint('PHASE 3: ' + str(i) + '/30 MIN')
    time.sleep(60*multiplier)

write(s, 'APPL:DC DEF, DEF, 0')
time.sleep(1)
myprint("COMPLETE! FUNCTION GENERATOR OFF.")
end_time = str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
myprint('COMPLETED AT: '+end_time)

